vim.opt.guicursor = ""
vim.scriptencoding ="utf-8"
vim.opt.encoding ="utf-8"
vim.opt.fileencoding ="utf-8"
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.smartindent = true
vim.opt.colorcolumn = "80"
vim.opt.mouse = "a"
vim.opt.undodir = os.getenv("HOME") .. "/.config/.nvim/undodir"
vim.opt.undofile = true
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.hidden = true
vim.opt.wrap = true
vim.opt.scrolloff = 5
vim.opt.termguicolors = true
vim.opt.updatetime = 50
vim.o.conceallevel = 1
vim.api.nvim_set_hl(0, "HelpBar", { link = "Normal" })
vim.api.nvim_set_hl(0, "HelpStar", { link = "Normal" })
--vim.api.loaded_node_provider = 0
--vim.api.loaded_python3_provider = 0
--vim.g.clipboard = 'osc52'

